[phases.setup]
nixPkgs = ["...", "nodejs_20"]

[phases.install]
cmds = ["...", "cd frontend && npm install"]

[phases.build]
cmds = ["...", "cd frontend && npm run build"]

[start]
cmd = "gunicorn -w 1 -b 0.0.0.0:$PORT server:app"